In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd

In [3]:
# Descripcion del dataset: https://github.com/SistemasMapache/Covid19arData/blob/master/diccionariodatos.md

data_folder = '../dataset/sistemasMapache/'
historico_filename = 'Covid19arData - historico.csv'
historico_path = data_folder + historico_filename

In [4]:
df_historico = pd.read_csv(historico_path)

In [5]:
df_historico.head()

,fecha,dia_inicio,dia_cuarentena_dnu260,osm_admin_level_2,osm_admin_level_4,osm_admin_level_8,tot_casosconf,nue_casosconf_diff,tot_fallecidos,nue_fallecidos_diff,tot_recuperados,tot_terapia,test_RT-PCR_negativos,test_RT-PCR_total,transmision_tipo,informe_tipo,informe_link,observacion,covid19argentina_admin_level_4
0,2/03/2020,1,NaN,Argentina,CABA,NaN,1,1,0,0,NaN,NaN,NaN,NaN,importado,NaN,https://www.infobae.com/coronavirus/2020/03/03...,no hay informe,capital-federal
1,3/03/2020,2,NaN,Argentina,Indeterminado,NaN,1,0,0,0,NaN,NaN,NaN,NaN,importado,NaN,NaN,no hay informe,no-data
2,4/03/2020,3,NaN,Argentina,Indeterminado,NaN,1,0,0,0,NaN,NaN,NaN,NaN,importado,NaN,NaN,no hay informe,no-data
3,5/03/2020,4,NaN,Argentina,Buenos Aires,NaN,2,1,2,2,NaN,NaN,NaN,NaN,importado,informe nacional,https://www.argentina.gob.ar/sites/default/fil...,NaN,buenos-aires
4,6/03/2020,5,NaN,Argentina,Indeterminado,NaN,2,0,2,0,NaN,NaN,NaN,NaN,importado,informe nacional,https://www.argentina.gob.ar/sites/default/fil...,NaN,no-data

In [6]:
df_historico.fillna(0)

,fecha,dia_inicio,dia_cuarentena_dnu260,osm_admin_level_2,osm_admin_level_4,osm_admin_level_8,tot_casosconf,nue_casosconf_diff,tot_fallecidos,nue_fallecidos_diff,tot_recuperados,tot_terapia,test_RT-PCR_negativos,test_RT-PCR_total,transmision_tipo,informe_tipo,informe_link,observacion,covid19argentina_admin_level_4
0,2/03/2020,1,0.0,Argentina,CABA,0,1,1,0,0,0.0,0.0,0.0,0.0,importado,0,https://www.infobae.com/coronavirus/2020/03/03...,no hay informe,capital-federal
1,3/03/2020,2,0.0,Argentina,Indeterminado,0,1,0,0,0,0.0,0.0,0.0,0.0,importado,0,0,no hay informe,no-data
2,4/03/2020,3,0.0,Argentina,Indeterminado,0,1,0,0,0,0.0,0.0,0.0,0.0,importado,0,0,no hay informe,no-data
3,5/03/2020,4,0.0,Argentina,Buenos Aires,0,2,1,2,2,0.0,0.0,0.0,0.0,importado,informe nacional,https://www.argentina.gob.ar/sites/default/fil...,0,buenos-aires
4,6/03/2020,5,0.0,Argentina,Indeterminado,0,2,0,2,0,0.0,0.0,0.0,0.0,importado,informe nacional,https://www.argentina.gob.ar/sites/default/fil...,0,no-data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1143,3/06/2020,91,75.0,Argentina,Santa Cruz,0,19265,0,583,0,0.0,0.0,0.0,0.0,0,0,0,0,0
1144,3/06/2020,91,75.0,Argentina,Santa Fe,0,19268,3,583,0,0.0,0.0,0.0,0.0,0,0,0,0,0
1145,3/06/2020,91,75.0,Argentina,Tierra del Fuego,0,19268,0,583,0,0.0,0.0,0.0,0.0,0,0,0,0,0
1146,3/06/2020,91,75.0,Argentina,Tucumán,0,19268,0,583,0,0.0,0.0,0.0,0.0,0,0,0,0,0
1147,3/06/2020,91,75.0,Argentina,Indeterminado,0,19268,0,583,0,0.0,0.0,0.0,0.0,0,0,0,0,0

In [7]:
df_historico = df_historico[['fecha','osm_admin_level_4','nue_casosconf_diff','nue_fallecidos_diff']]

In [8]:
df_historico.head()

       fecha osm_admin_level_4  nue_casosconf_diff  nue_fallecidos_diff
0  2/03/2020              CABA                   1                    0
1  3/03/2020     Indeterminado                   0                    0
2  4/03/2020     Indeterminado                   0                    0
3  5/03/2020      Buenos Aires                   1                    2
4  6/03/2020     Indeterminado                   0                    0

In [9]:
df_historico.drop(df_historico[df_historico.osm_admin_level_4 == 'Indeterminado'].index, inplace=True)

In [10]:
df_historico.drop(df_historico[df_historico.osm_admin_level_4.isna()].index, inplace=True)

In [11]:
df_historico.fecha = pd.to_datetime(df_historico.fecha.astype(str), format='%d/%m/%Y')

In [12]:
df_historico

          fecha osm_admin_level_4  nue_casosconf_diff  nue_fallecidos_diff
0    2020-03-02              CABA                   1                    0
3    2020-03-05      Buenos Aires                   1                    2
6    2020-03-08      Buenos Aires                   8                    0
7    2020-03-09              CABA                   1                    1
8    2020-03-09          San Luis                   2                    0
...         ...               ...                 ...                  ...
1142 2020-06-03             Salta                   0                    0
1143 2020-06-03        Santa Cruz                   0                    0
1144 2020-06-03          Santa Fe                   3                    0
1145 2020-06-03  Tierra del Fuego                   0                    0
1146 2020-06-03           Tucumán                   0                    0

[1064 rows x 4 columns]

In [13]:
df_historico.rename(columns={
    'fecha':'index',
    'osm_admin_level_4':'Province/State'
}, inplace=True)

In [14]:
df_historico.head()

       index Province/State  nue_casosconf_diff  nue_fallecidos_diff
0 2020-03-02           CABA                   1                    0
3 2020-03-05   Buenos Aires                   1                    2
6 2020-03-08   Buenos Aires                   8                    0
7 2020-03-09           CABA                   1                    1
8 2020-03-09       San Luis                   2                    0

In [15]:
df_historico.sort_values(by=['Province/State', 'index'], ascending=True)

          index Province/State  nue_casosconf_diff  nue_fallecidos_diff
3    2020-03-05   Buenos Aires                   1                    2
6    2020-03-08   Buenos Aires                   8                    0
11   2020-03-10   Buenos Aires                   1                    0
13   2020-03-11   Buenos Aires                   1                    0
16   2020-03-13   Buenos Aires                   1                    0
...         ...            ...                 ...                  ...
1066 2020-05-30        Tucumán                   1                    0
1086 2020-05-31        Tucumán                   0                    0
1106 2020-06-01        Tucumán                   0                    0
1126 2020-06-02        Tucumán                   0                    0
1146 2020-06-03        Tucumán                   0                    0

[1064 rows x 4 columns]

In [16]:
#df_datasource = df_datasource.groupby(['Province/State', 'index']).sum().groupby(level=0).cumsum().reset_index()

In [17]:
df_historico

          index    Province/State  nue_casosconf_diff  nue_fallecidos_diff
0    2020-03-02              CABA                   1                    0
3    2020-03-05      Buenos Aires                   1                    2
6    2020-03-08      Buenos Aires                   8                    0
7    2020-03-09              CABA                   1                    1
8    2020-03-09          San Luis                   2                    0
...         ...               ...                 ...                  ...
1142 2020-06-03             Salta                   0                    0
1143 2020-06-03        Santa Cruz                   0                    0
1144 2020-06-03          Santa Fe                   3                    0
1145 2020-06-03  Tierra del Fuego                   0                    0
1146 2020-06-03           Tucumán                   0                    0

[1064 rows x 4 columns]

In [18]:
#df_datasource["Province/State"] = df_datasource["Province/State"].str.replace("-", " ", case = False)

In [19]:
df_deaths = df_historico[['index','Province/State','nue_fallecidos_diff']]
df_confirmed = df_historico[['index','Province/State','nue_casosconf_diff']]

In [20]:
df_deaths.head(20)

        index    Province/State  nue_fallecidos_diff
0  2020-03-02              CABA                    0
3  2020-03-05      Buenos Aires                    2
6  2020-03-08      Buenos Aires                    0
7  2020-03-09              CABA                    1
8  2020-03-09          San Luis                    0
9  2020-03-09             Chaco                    0
10 2020-03-09         Río Negro                    0
11 2020-03-10      Buenos Aires                    0
12 2020-03-10              CABA                    1
13 2020-03-11      Buenos Aires                    0
14 2020-03-11              CABA                    0
15 2020-03-12              CABA                    0
16 2020-03-13      Buenos Aires                    0
17 2020-03-13              CABA                    1
18 2020-03-14              CABA                    0
19 2020-03-15              CABA                    0
20 2020-03-15             Chaco                    0
21 2020-03-15  Tierra del Fuego                    0
22 2020-03-15      Buenos Aires                    0
23 2020-03-16              CABA                    0

In [21]:
df_confirmed.head()

       index Province/State  nue_casosconf_diff
0 2020-03-02           CABA                   1
3 2020-03-05   Buenos Aires                   1
6 2020-03-08   Buenos Aires                   8
7 2020-03-09           CABA                   1
8 2020-03-09       San Luis                   2

In [22]:
#df_confirmed['index'] = df_confirmed['index'].str[:-2]
#df_deaths['index'] = df_deaths['index'].str[:-2]

In [23]:
df_confirmed

          index    Province/State  nue_casosconf_diff
0    2020-03-02              CABA                   1
3    2020-03-05      Buenos Aires                   1
6    2020-03-08      Buenos Aires                   8
7    2020-03-09              CABA                   1
8    2020-03-09          San Luis                   2
...         ...               ...                 ...
1142 2020-06-03             Salta                   0
1143 2020-06-03        Santa Cruz                   0
1144 2020-06-03          Santa Fe                   3
1145 2020-06-03  Tierra del Fuego                   0
1146 2020-06-03           Tucumán                   0

[1064 rows x 3 columns]

In [24]:
df_confirmed['index'] = df_confirmed["index"].dt.strftime('%-m/%-d/%y')
df_deaths['index'] = df_deaths["index"].dt.strftime('%-m/%-d/%y')

In [25]:
df_deaths.head()

    index Province/State  nue_fallecidos_diff
0  3/2/20           CABA                    0
3  3/5/20   Buenos Aires                    2
6  3/8/20   Buenos Aires                    0
7  3/9/20           CABA                    1
8  3/9/20       San Luis                    0

In [26]:
#df_confirmed.set_index(['index','Province/State']).stack().groupby(level=0).describe().unstack()
df_confirmed.groupby(['index','Province/State'])['nue_casosconf_diff'].sum().reset_index()

       index    Province/State  nue_casosconf_diff
0    3/10/20      Buenos Aires                   1
1    3/10/20              CABA                   1
2    3/11/20      Buenos Aires                   1
3    3/11/20              CABA                   1
4    3/12/20              CABA                  10
..       ...               ...                 ...
981   6/3/20          San Juan                   0
982   6/3/20        Santa Cruz                   0
983   6/3/20          Santa Fe                   3
984   6/3/20  Tierra del Fuego                   0
985   6/3/20           Tucumán                   0

[986 rows x 3 columns]

In [27]:
df_confirmed

       index    Province/State  nue_casosconf_diff
0     3/2/20              CABA                   1
3     3/5/20      Buenos Aires                   1
6     3/8/20      Buenos Aires                   8
7     3/9/20              CABA                   1
8     3/9/20          San Luis                   2
...      ...               ...                 ...
1142  6/3/20             Salta                   0
1143  6/3/20        Santa Cruz                   0
1144  6/3/20          Santa Fe                   3
1145  6/3/20  Tierra del Fuego                   0
1146  6/3/20           Tucumán                   0

[1064 rows x 3 columns]

In [28]:
import numpy as np

In [29]:
df_confirmed_pivot = pd.pivot_table(df_confirmed, values='nue_casosconf_diff', index=['Province/State'], columns='index', aggfunc=np.sum).fillna(0)

In [30]:
df_deaths_pivot = pd.pivot_table(df_deaths, values='nue_fallecidos_diff', index=['Province/State'], columns='index', aggfunc=np.sum).fillna(0)

In [31]:
#df_confirmed_pivot = pd.pivot(data = df_confirmed, index='Province/State', columns='index', values='nue_fallecidos_diff', ).fillna(0)

In [32]:
#df_deaths_pivot = df_deaths.pivot(index='Province/State', columns='index', values='nue_fallecidos_diff').fillna(0)

In [33]:
df_confirmed_pivot

index,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,...,5/31/20,5/4/20,5/5/20,5/6/20,5/7/20,5/8/20,5/9/20,6/1/20,6/2/20,6/3/20
Province/State,,,,,,,,,,,,,,,,,,,,,
Buenos Aires,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,6.0,14.0,...,254.0,38.0,58.0,63.0,50.0,77.0,60.0,252.0,488.0,442.0
CABA,1.0,1.0,10.0,2.0,11.0,6.0,5.0,4.0,10.0,8.0,...,358.0,43.0,57.0,102.0,77.0,130.0,83.0,274.0,371.0,467.0
Chaco,0.0,0.0,0.0,0.0,0.0,4.0,3.0,1.0,1.0,2.0,...,13.0,5.0,11.0,8.0,26.0,26.0,9.0,3.0,30.0,6.0
Chubut,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Corrientes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,3.0,1.0,1.0,1.0,6.0,2.0,0.0
Córdoba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,2.0,...,2.0,6.0,1.0,5.0,4.0,2.0,6.0,0.0,1.0,1.0
Entre Ríos,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0
Jujuy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
La Pampa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
La Rioja,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
Mendoza,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,8.0,0.0,0.0
Misiones,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Neuquén,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,3.0,10.0
Río Negro,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,...,4.0,7.0,4.0,6.0,3.0,2.0,4.0,11.0,3.0,16.0
Salta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0
San Juan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
San Luis,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Santa Cruz,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Santa Fe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0
Santiago del Estero,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Tierra del Fuego,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Tucumán,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
df_confirmed_pivot.insert(0, 'Country/Region', 'Argentina')
df_deaths_pivot.insert(0, 'Country/Region', 'Argentina')

In [35]:
df_confirmed_pivot.head(30)

index,Country/Region,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,...,5/31/20,5/4/20,5/5/20,5/6/20,5/7/20,5/8/20,5/9/20,6/1/20,6/2/20,6/3/20
Province/State,,,,,,,,,,,,,,,,,,,,,
Buenos Aires,Argentina,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,6.0,...,254.0,38.0,58.0,63.0,50.0,77.0,60.0,252.0,488.0,442.0
CABA,Argentina,1.0,1.0,10.0,2.0,11.0,6.0,5.0,4.0,10.0,...,358.0,43.0,57.0,102.0,77.0,130.0,83.0,274.0,371.0,467.0
Chaco,Argentina,0.0,0.0,0.0,0.0,0.0,4.0,3.0,1.0,1.0,...,13.0,5.0,11.0,8.0,26.0,26.0,9.0,3.0,30.0,6.0
Chubut,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Corrientes,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,3.0,1.0,1.0,1.0,6.0,2.0,0.0
Córdoba,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,...,2.0,6.0,1.0,5.0,4.0,2.0,6.0,0.0,1.0,1.0
Entre Ríos,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0
Jujuy,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
La Pampa,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
La Rioja,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
Mendoza,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,8.0,0.0,0.0
Misiones,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Neuquén,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,3.0,10.0
Río Negro,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,7.0,4.0,6.0,3.0,2.0,4.0,11.0,3.0,16.0
Salta,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0
San Juan,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
San Luis,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Santa Cruz,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Santa Fe,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0
Santiago del Estero,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Tierra del Fuego,Argentina,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Tucumán,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
df_confirmed_pivot = df_confirmed_pivot.reset_index()
df_deaths_pivot = df_deaths_pivot.reset_index()

In [37]:
df_confirmed_pivot

index,Province/State,Country/Region,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,...,5/31/20,5/4/20,5/5/20,5/6/20,5/7/20,5/8/20,5/9/20,6/1/20,6/2/20,6/3/20
0,Buenos Aires,Argentina,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,...,254.0,38.0,58.0,63.0,50.0,77.0,60.0,252.0,488.0,442.0
1,CABA,Argentina,1.0,1.0,10.0,2.0,11.0,6.0,5.0,4.0,...,358.0,43.0,57.0,102.0,77.0,130.0,83.0,274.0,371.0,467.0
2,Chaco,Argentina,0.0,0.0,0.0,0.0,0.0,4.0,3.0,1.0,...,13.0,5.0,11.0,8.0,26.0,26.0,9.0,3.0,30.0,6.0
3,Chubut,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,Corrientes,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,3.0,1.0,1.0,1.0,6.0,2.0,0.0
5,Córdoba,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,2.0,6.0,1.0,5.0,4.0,2.0,6.0,0.0,1.0,1.0
6,Entre Ríos,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0
7,Jujuy,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,La Pampa,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,La Rioja,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
10,Mendoza,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,8.0,0.0,0.0
11,Misiones,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
12,Neuquén,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,3.0,10.0
13,Río Negro,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,4.0,7.0,4.0,6.0,3.0,2.0,4.0,11.0,3.0,16.0
14,Salta,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0
15,San Juan,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
16,San Luis,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,Santa Cruz,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
18,Santa Fe,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0
19,Santiago del Estero,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,Tierra del Fuego,Argentina,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21,Tucumán,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
df_deaths_pivot

index,Province/State,Country/Region,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,...,5/31/20,5/4/20,5/5/20,5/6/20,5/7/20,5/8/20,5/9/20,6/1/20,6/2/20,6/3/20
0,Buenos Aires,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,7.0,1.0,5.0,6.0,5.0,4.0,5.0,8.0,6.0
1,CABA,Argentina,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,5.0,4.0,1.0,2.0,2.0,6.0,2.0,8.0,3.0,5.0
2,Chaco,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,3.0,2.0,1.0
3,Chubut,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Corrientes,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Córdoba,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
6,Entre Ríos,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Jujuy,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,La Pampa,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,La Rioja,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10,Mendoza,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Misiones,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,Neuquén,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Río Negro,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
14,Salta,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,San Juan,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,San Luis,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,Santa Cruz,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Santa Fe,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19,Santiago del Estero,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,Tierra del Fuego,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,Tucumán,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
df_confirmed_pivot.iloc[0,2]

1.0

In [40]:
df_confirmed_pivot.iloc[0,2] = 16

In [41]:
len(df_confirmed_pivot)

22

In [42]:
for r in range(0,len(df_confirmed_pivot)):
    for c in range(3,len(df_confirmed_pivot.columns)):
        df_confirmed_pivot.iloc[r,c] = df_confirmed_pivot.iloc[r,c - 1] + df_confirmed_pivot.iloc[r,c]

In [43]:
for r in range(0,len(df_deaths_pivot)):
    for c in range(3,len(df_deaths_pivot.columns)):
        df_deaths_pivot.iloc[r,c] = df_deaths_pivot.iloc[r,c - 1] + df_deaths_pivot.iloc[r,c]

In [44]:
df_confirmed_pivot

index,Province/State,Country/Region,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,...,5/31/20,5/4/20,5/5/20,5/6/20,5/7/20,5/8/20,5/9/20,6/1/20,6/2/20,6/3/20
0,Buenos Aires,Argentina,16.0,17.0,17.0,18.0,18.0,19.0,20.0,21.0,...,5561.0,5599.0,5657.0,5720.0,5770.0,5847.0,5907.0,6159.0,6647.0,7089.0
1,CABA,Argentina,1.0,2.0,12.0,14.0,25.0,31.0,36.0,40.0,...,7714.0,7757.0,7814.0,7916.0,7993.0,8123.0,8206.0,8480.0,8851.0,9318.0
2,Chaco,Argentina,0.0,0.0,0.0,0.0,0.0,4.0,7.0,8.0,...,802.0,807.0,818.0,826.0,852.0,878.0,887.0,890.0,920.0,926.0
3,Chubut,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,11.0
4,Corrientes,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,82.0,82.0,82.0,85.0,86.0,87.0,88.0,94.0,96.0,96.0
5,Córdoba,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,434.0,440.0,441.0,446.0,450.0,452.0,458.0,458.0,459.0,460.0
6,Entre Ríos,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,30.0,30.0,31.0,31.0,31.0,31.0,31.0,31.0,33.0,35.0
7,Jujuy,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
8,La Pampa,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
9,La Rioja,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,59.0,60.0,60.0,61.0,62.0,63.0,63.0,63.0,63.0,63.0
10,Mendoza,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,90.0,90.0,91.0,91.0,91.0,92.0,92.0,100.0,100.0,100.0
11,Misiones,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,27.0,28.0,28.0,28.0,28.0,28.0,28.0,28.0,28.0,29.0
12,Neuquén,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,133.0,133.0,133.0,133.0,133.0,133.0,134.0,137.0,140.0,150.0
13,Río Negro,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,370.0,377.0,381.0,387.0,390.0,392.0,396.0,407.0,410.0,426.0
14,Salta,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,11.0,15.0,15.0
15,San Juan,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0
16,San Luis,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0
17,Santa Cruz,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,50.0,50.0,50.0,50.0,50.0,50.0,50.0,51.0,51.0,51.0
18,Santa Fe,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,261.0,261.0,262.0,262.0,262.0,262.0,262.0,265.0,265.0,268.0
19,Santiago del Estero,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0
20,Tierra del Fuego,Argentina,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,148.0,148.0,148.0,148.0,148.0,148.0,149.0,149.0,149.0,149.0
21,Tucumán,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,45.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0

In [45]:
df_deaths_pivot

index,Province/State,Country/Region,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,...,5/31/20,5/4/20,5/5/20,5/6/20,5/7/20,5/8/20,5/9/20,6/1/20,6/2/20,6/3/20
0,Buenos Aires,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,198.0,205.0,206.0,211.0,217.0,222.0,226.0,231.0,239.0,245.0
1,CABA,Argentina,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,...,168.0,172.0,173.0,175.0,177.0,183.0,185.0,193.0,196.0,201.0
2,Chaco,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,50.0,51.0,51.0,52.0,52.0,52.0,52.0,55.0,57.0,58.0
3,Chubut,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Corrientes,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Córdoba,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,24.0,26.0,28.0,28.0,28.0,28.0,28.0,29.0,29.0,30.0
6,Entre Ríos,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Jujuy,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,La Pampa,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,La Rioja,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,6.0,6.0,6.0,6.0,6.0,7.0,7.0,7.0,7.0
10,Mendoza,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
11,Misiones,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
12,Neuquén,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
13,Río Negro,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,16.0,16.0,16.0,17.0,17.0,17.0,17.0,17.0,17.0,18.0
14,Salta,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,San Juan,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,San Luis,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,Santa Cruz,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Santa Fe,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0
19,Santiago del Estero,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,Tierra del Fuego,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,Tucumán,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0

-----------------------------

In [46]:
data_folder = '../dataset/johnsHopkins/'

confirmed_filename = 'time_series_covid19_confirmed_global.csv'
deaths_filename = 'time_series_covid19_deaths_global.csv'

confirmed_path = data_folder + confirmed_filename
deaths_path = data_folder + deaths_filename

In [47]:
df_confirmed = pd.read_csv(confirmed_path)
df_deaths = pd.read_csv(deaths_path)

In [48]:
df_confirmed.head(10)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,5/25/20,5/26/20,5/27/20,5/28/20,5/29/20,5/30/20,5/31/20,6/1/20,6/2/20,6/3/20
0,NaN,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,11173,11831,12456,13036,13659,14525,15205,15750,16509,17267
1,NaN,Albania,41.1533,20.1683,0,0,0,0,0,0,...,1004,1029,1050,1076,1099,1122,1137,1143,1164,1184
2,NaN,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,8503,8697,8857,8997,9134,9267,9394,9513,9626,9733
3,NaN,Andorra,42.5063,1.5218,0,0,0,0,0,0,...,763,763,763,763,764,764,764,765,844,851
4,NaN,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,70,70,71,74,81,84,86,86,86,86
5,NaN,Antigua and Barbuda,17.0608,-61.7964,0,0,0,0,0,0,...,25,25,25,25,25,25,26,26,26,26
6,NaN,Argentina,-38.4161,-63.6167,0,0,0,0,0,0,...,12628,13228,13933,14702,15419,16214,16851,17415,18319,19268
7,NaN,Armenia,40.0691,45.0382,0,0,0,0,0,0,...,7113,7402,7774,8216,8676,8927,9282,9492,10009,10524
8,Australian Capital Territory,Australia,-35.4735,149.0124,0,0,0,0,0,0,...,107,107,107,107,107,107,107,107,107,107
9,New South Wales,Australia,-33.8688,151.2093,0,0,0,0,3,4,...,3092,3089,3090,3092,3092,3095,3098,3104,3104,3106

In [49]:
del df_confirmed['Lat']
del df_confirmed['Long']

del df_deaths['Lat']
del df_deaths['Long']

In [50]:
df_confirmed.drop(df_confirmed[df_confirmed['Country/Region'] == 'Argentina'].index, inplace=True)
df_deaths.drop(df_deaths[df_deaths['Country/Region'] == 'Argentina'].index, inplace=True)

In [51]:
df_confirmed

,Province/State,Country/Region,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,5/25/20,5/26/20,5/27/20,5/28/20,5/29/20,5/30/20,5/31/20,6/1/20,6/2/20,6/3/20
0,NaN,Afghanistan,0,0,0,0,0,0,0,0,...,11173,11831,12456,13036,13659,14525,15205,15750,16509,17267
1,NaN,Albania,0,0,0,0,0,0,0,0,...,1004,1029,1050,1076,1099,1122,1137,1143,1164,1184
2,NaN,Algeria,0,0,0,0,0,0,0,0,...,8503,8697,8857,8997,9134,9267,9394,9513,9626,9733
3,NaN,Andorra,0,0,0,0,0,0,0,0,...,763,763,763,763,764,764,764,765,844,851
4,NaN,Angola,0,0,0,0,0,0,0,0,...,70,70,71,74,81,84,86,86,86,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,NaN,Sao Tome and Principe,0,0,0,0,0,0,0,0,...,299,441,443,458,463,479,483,484,484,484
262,NaN,Yemen,0,0,0,0,0,0,0,0,...,233,249,256,278,283,310,323,354,399,419
263,NaN,Comoros,0,0,0,0,0,0,0,0,...,87,87,87,87,87,106,106,106,132,132
264,NaN,Tajikistan,0,0,0,0,0,0,0,0,...,3100,3266,3424,3563,3686,3807,3930,4013,4100,4191
265,NaN,Lesotho,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,4

In [52]:
df_confirmed_pivot

index,Province/State,Country/Region,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,...,5/31/20,5/4/20,5/5/20,5/6/20,5/7/20,5/8/20,5/9/20,6/1/20,6/2/20,6/3/20
0,Buenos Aires,Argentina,16.0,17.0,17.0,18.0,18.0,19.0,20.0,21.0,...,5561.0,5599.0,5657.0,5720.0,5770.0,5847.0,5907.0,6159.0,6647.0,7089.0
1,CABA,Argentina,1.0,2.0,12.0,14.0,25.0,31.0,36.0,40.0,...,7714.0,7757.0,7814.0,7916.0,7993.0,8123.0,8206.0,8480.0,8851.0,9318.0
2,Chaco,Argentina,0.0,0.0,0.0,0.0,0.0,4.0,7.0,8.0,...,802.0,807.0,818.0,826.0,852.0,878.0,887.0,890.0,920.0,926.0
3,Chubut,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,11.0
4,Corrientes,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,82.0,82.0,82.0,85.0,86.0,87.0,88.0,94.0,96.0,96.0
5,Córdoba,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,434.0,440.0,441.0,446.0,450.0,452.0,458.0,458.0,459.0,460.0
6,Entre Ríos,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,30.0,30.0,31.0,31.0,31.0,31.0,31.0,31.0,33.0,35.0
7,Jujuy,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
8,La Pampa,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
9,La Rioja,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,59.0,60.0,60.0,61.0,62.0,63.0,63.0,63.0,63.0,63.0
10,Mendoza,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,90.0,90.0,91.0,91.0,91.0,92.0,92.0,100.0,100.0,100.0
11,Misiones,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,27.0,28.0,28.0,28.0,28.0,28.0,28.0,28.0,28.0,29.0
12,Neuquén,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,133.0,133.0,133.0,133.0,133.0,133.0,134.0,137.0,140.0,150.0
13,Río Negro,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,370.0,377.0,381.0,387.0,390.0,392.0,396.0,407.0,410.0,426.0
14,Salta,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,11.0,15.0,15.0
15,San Juan,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0
16,San Luis,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0
17,Santa Cruz,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,50.0,50.0,50.0,50.0,50.0,50.0,50.0,51.0,51.0,51.0
18,Santa Fe,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,261.0,261.0,262.0,262.0,262.0,262.0,262.0,265.0,265.0,268.0
19,Santiago del Estero,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0
20,Tierra del Fuego,Argentina,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,148.0,148.0,148.0,148.0,148.0,148.0,149.0,149.0,149.0,149.0
21,Tucumán,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,45.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0

In [53]:
result_confirmed = pd.concat([df_confirmed, df_confirmed_pivot], axis=0, ignore_index=True).fillna(0)
result_deaths = pd.concat([df_deaths, df_deaths], axis=0, ignore_index=True).fillna(0)
#result = pd.concat(frames)

In [54]:
result_confirmed = result_confirmed.sort_values(by=['Country/Region'])
result_deaths = result_deaths.sort_values(by=['Country/Region'])

In [55]:
result_confirmed

,Province/State,Country/Region,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,5/25/20,5/26/20,5/27/20,5/28/20,5/29/20,5/30/20,5/31/20,6/1/20,6/2/20,6/3/20
0,0,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11173.0,11831.0,12456.0,13036.0,13659.0,14525.0,15205.0,15750.0,16509.0,17267.0
1,0,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1004.0,1029.0,1050.0,1076.0,1099.0,1122.0,1137.0,1143.0,1164.0,1184.0
2,0,Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8503.0,8697.0,8857.0,8997.0,9134.0,9267.0,9394.0,9513.0,9626.0,9733.0
3,0,Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,763.0,763.0,763.0,763.0,764.0,764.0,764.0,765.0,844.0,851.0
4,0,Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,70.0,70.0,71.0,74.0,81.0,84.0,86.0,86.0,86.0,86.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,0,West Bank and Gaza,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,423.0,429.0,434.0,446.0,446.0,447.0,448.0,449.0,451.0,457.0
259,0,Western Sahara,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0
261,0,Yemen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,233.0,249.0,256.0,278.0,283.0,310.0,323.0,354.0,399.0,419.0
228,0,Zambia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,920.0,920.0,1057.0,1057.0,1057.0,1057.0,1057.0,1089.0,1089.0,1089.0
229,0,Zimbabwe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,56.0,56.0,132.0,149.0,149.0,174.0,178.0,203.0,206.0,222.0

In [56]:
result_confirmed[result_confirmed['Country/Region'] == 'Argentina']

,Province/State,Country/Region,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,5/25/20,5/26/20,5/27/20,5/28/20,5/29/20,5/30/20,5/31/20,6/1/20,6/2/20,6/3/20
266,CABA,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5334.0,5661.0,6022.0,6447.0,6848.0,7356.0,7714.0,8480.0,8851.0,9318.0
267,Chaco,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,667.0,690.0,706.0,734.0,760.0,789.0,802.0,890.0,920.0,926.0
268,Chubut,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,5.0,5.0,8.0,8.0,10.0,10.0,10.0,10.0,11.0
269,Corrientes,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,72.0,72.0,74.0,75.0,81.0,81.0,82.0,94.0,96.0,96.0
270,Córdoba,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,434.0,434.0,434.0,433.0,431.0,432.0,434.0,458.0,459.0,460.0
271,Entre Ríos,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,26.0,26.0,26.0,27.0,27.0,30.0,30.0,31.0,33.0,35.0
272,Jujuy,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,5.0,5.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
273,La Pampa,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
274,La Rioja,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,59.0,59.0,59.0,59.0,59.0,59.0,59.0,63.0,63.0,63.0
277,Neuquén,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,115.0,122.0,124.0,127.0,129.0,130.0,133.0,137.0,140.0,150.0
276,Misiones,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,24.0,24.0,24.0,26.0,26.0,26.0,27.0,28.0,28.0,29.0
265,Buenos Aires,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3850.0,4086.0,4401.0,4700.0,4973.0,5307.0,5561.0,6159.0,6647.0,7089.0
278,Río Negro,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,324.0,328.0,336.0,343.0,355.0,366.0,370.0,407.0,410.0,426.0
279,Salta,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,7.0,7.0,7.0,7.0,8.0,8.0,11.0,15.0,15.0
280,San Juan,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,3.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0
281,San Luis,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0
282,Santa Cruz,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,49.0,49.0,49.0,49.0,49.0,49.0,50.0,51.0,51.0,51.0
283,Santa Fe,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,258.0,259.0,259.0,259.0,259.0,261.0,261.0,265.0,265.0,268.0
284,Santiago del Estero,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0
275,Mendoza,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,87.0,87.0,87.0,87.0,87.0,90.0,90.0,100.0,100.0,100.0
285,Tierra del Fuego,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,145.0,145.0,146.0,146.0,146.0,148.0,148.0,149.0,149.0,149.0
286,Tucumán,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,44.0,44.0,44.0,44.0,44.0,45.0,45.0,48.0,48.0,48.0

## Actividades

0) 
    a) Analizar el datasets (columnas y datos de las filas), calcular estadísticos descriptivos, analizar valores nulos y su significado. Concluir al respecto sobre la cantidad/calidad/estructura de los datos. 
    
    b) Identificar eventos anómalos y analizar la posible causa de acuerdo a la fecha

1) Analizar situación en nuestra provincia vs otras considerando cantidad de infectados y fallecidos. Calcular indicadores que resulten de interes de acuerdo al problema.

2) Agrupar datos de provincias a modo de obtener valores totalizados por país.

3) 
    a) Graficar evolución de cantidad de casos de nuestro país y países de la región con respecto al tiempo. 
    
    b) Realizar análisis similar considerando países de diferentes continentes. Concluir acerca de formas de las curvas de los países analizados y su etapa en el control del covid. 

4) Realizar grafico comparativo de cantidad de casos por país de modo que resulte fácil identificar la situación de cada uno de éstos. Replicar el mismo considerando provincias.

Opcional: Generar gráfico de avance de cantidad de infectados mundial animado por tiempo (https://plotly.com/python/sliders/)